In [1]:
import json


In [2]:
import json
import os
with open('Lagain_GSA_database/Global/lagain_db_filtered.json/lagain_db_filtered.json', 'r') as myfile:
    data=myfile.read()
    obj = json.loads(data)


In [3]:
import pandas as pd
data = pd.read_csv ("RobbinsCraters_20121016.tsv", sep = '\t',encoding = 'unicode_escape', engine ='python')

In [4]:
len(data)

384345

In [5]:
data.head()

CRATER_ID  LATITUDE_CIRCLE_IMAGE  LONGITUDE_CIRCLE_IMAGE  \
0  01-000000                 84.367                 108.746   
1  01-000001                 72.760                 164.464   
2  01-000002                 69.244                 -27.240   
3  01-000003                 70.107                 160.575   
4  01-000004                 77.996                  95.617   

   LATITUDE_ELLIPSE_IMAGE  LONGITUDE_ELLIPSE_IMAGE  DIAM_CIRCLE_IMAGE  \
0                  84.750                  108.663              82.10   
1                  72.784                  164.464              82.02   
2                  69.241                  -27.235              79.63   
3                  70.151                  160.575              74.81   
4                  77.998                   95.615              73.53   

   DIAM_CIRCLE_SD_IMAGE  DIAM_ELLIPSE_MAJOR_IMAGE  DIAM_ELLIPSE_MINOR_IMAGE  \
0                  0.26                     82.97                     69.43   
1                  0.09                     84.17                     79.91   
2                   NaN                     84.36                     75.28   
3                  0.05                     75.12                     74.58   
4                  0.23                     77.28                     70.13   

   DIAM_ELLIPSE_ECCEN_IMAGE  ...  LAYER_4_AREA  LAYER_4_LOBATENESS  \
0                      0.55  ...           NaN                 NaN   
1                      0.31  ...           NaN                 NaN   
2                      0.45  ...           NaN                 NaN   
3                      0.12  ...           NaN                 NaN   
4                      0.42  ...           NaN                 NaN   

   LAYER_4_EJECTARAD_EQUIV  LAYER_4_EJECTARAD_REL  LAYER_5_PERIMETER  \
0                      NaN                    NaN                NaN   
1                      NaN                    NaN                NaN   
2                      NaN                    NaN                NaN   
3                      NaN                    NaN                NaN   
4                      NaN                    NaN                NaN   

   LAYER_5_AREA  LAYER_5_LOBATENESS  LAYER_5_EJECTARAD_EQUIV  \
0           NaN                 NaN                      NaN   
1           NaN                 NaN                      NaN   
2           NaN                 NaN                      NaN   
3           NaN                 NaN                      NaN   
4           NaN                 NaN                      NaN   

   LAYER_5_EJECTARAD_REL  CRATER_NAME  
0                    NaN          NaN  
1                    NaN      Korolev  
2                    NaN          NaN  
3                    NaN          NaN  
4                    NaN          NaN  

[5 rows x 70 columns]

In [6]:
temp_dict = []
for x in obj['features']:
    temp_dict.append(x['properties'])

In [7]:
import pandas as pd
df = pd.DataFrame(temp_dict)

In [8]:
len(df)

376437

In [9]:
df.head()

CRATER_ID  RADIUS           X          Y  TYPE STATUS LRD_MORPH ORIGIN  \
0   200-007   500.0   23.671499 -43.584301   1.0  Other      None   None   
1   200-008   500.0   68.432404 -39.950500   1.0  Other      None   None   
2   200-009   500.0  177.154007  -0.758709   1.0  Other      None   None   
3   200-010   500.0   34.128899 -31.406401   1.0  Other      None   None   
4   100-001   500.0  -52.963100  47.302601   1.0  Other      None   None   

   ADDING  
0     1.0  
1     1.0  
2     1.0  
3     1.0  
4     1.0

In [10]:
df['STATUS'].value_counts()

Other        288117
Secondary     55307
Buried        24533
Layered        8480
Name: STATUS, dtype: int64

In [11]:
new_df = pd.merge(
    data,
    df,
    how="inner",
    on="CRATER_ID")

In [12]:
new_df.head()

CRATER_ID  LATITUDE_CIRCLE_IMAGE  LONGITUDE_CIRCLE_IMAGE  \
0  01-000001                 72.760                 164.464   
1  01-000007                 78.716                 -87.249   
2  01-000009                 69.371                  75.147   
3  01-000012                 77.170                -145.681   
4  01-000013                 72.260                 119.169   

   LATITUDE_ELLIPSE_IMAGE  LONGITUDE_ELLIPSE_IMAGE  DIAM_CIRCLE_IMAGE  \
0                  72.784                  164.464              82.02   
1                  78.915                  -87.307              63.57   
2                  69.083                   75.152              55.24   
3                  77.165                 -145.681              51.08   
4                  72.309                  119.169              49.78   

   DIAM_CIRCLE_SD_IMAGE  DIAM_ELLIPSE_MAJOR_IMAGE  DIAM_ELLIPSE_MINOR_IMAGE  \
0                  0.09                     84.17                     79.91   
1                  0.21                     66.86                     58.52   
2                  0.10                     56.33                     53.80   
3                  0.05                     51.77                     50.43   
4                  0.05                     50.56                     48.91   

   DIAM_ELLIPSE_ECCEN_IMAGE  ...  LAYER_5_EJECTARAD_REL  CRATER_NAME   RADIUS  \
0                      0.31  ...                    NaN      Korolev  41010.0   
1                      0.48  ...                    NaN          NaN  31785.0   
2                      0.30  ...                    NaN          NaN  27620.0   
3                      0.23  ...                    NaN        Dokka  25540.0   
4                      0.25  ...                    NaN          NaN  24890.0   

            X          Y  TYPE   STATUS  LRD_MORPH  ORIGIN  ADDING  
0  164.464004  72.760002   2.0  Layered        MLE    None     0.0  
1  -87.249000  78.716003   3.0   Buried       None    None     0.0  
2   75.147003  69.371002   3.0   Buried       None    None     0.0  
3 -145.681000  77.169998   1.0    Other       None    None     0.0  
4  119.168999  72.260002   3.0   Buried       None    None     0.0  

[5 rows x 78 columns]

In [100]:
import cv2
import numpy as np
img = np.zeros((7680,7680,3))

In [112]:

color_dict = {'Other':(0,255,0),'Secondary':(0,0,255),'Buried':(255,0,0),'Layered':(255,0,255)}

In [13]:
len(new_df)

376132

In [114]:
x = imgdim[0] * (cx - cdim[0]) / (cdim[1] - cdim[0])

In [157]:
len(f_df)

11862

In [158]:
f_df.head()

CRATER_ID  LATITUDE_CIRCLE_IMAGE  LONGITUDE_CIRCLE_IMAGE  \
203886  20-000001                 -2.508                  16.800   
203887  20-000003                -24.239                   1.074   
203888  20-000004                -16.799                  19.222   
203890  20-000007                -23.118                   8.507   
203892  20-000009                -18.235                   1.642   

        LATITUDE_ELLIPSE_IMAGE  LONGITUDE_ELLIPSE_IMAGE  DIAM_CIRCLE_IMAGE  \
203886                  -2.863                   16.794             445.76   
203887                 -24.226                    1.073             256.45   
203888                 -16.908                   19.217             236.06   
203890                 -23.743                    8.504             174.55   
203892                 -18.498                    1.636             166.40   

        DIAM_CIRCLE_SD_IMAGE  DIAM_ELLIPSE_MAJOR_IMAGE  \
203886                  0.38                    462.51   
203887                   NaN                    257.87   
203888                  0.24                    240.88   
203890                  0.25                    177.84   
203892                  0.25                    174.30   

        DIAM_ELLIPSE_MINOR_IMAGE  DIAM_ELLIPSE_ECCEN_IMAGE  ...  \
203886                    430.40                      0.37  ...   
203887                    255.39                      0.14  ...   
203888                    231.50                      0.28  ...   
203890                    172.22                      0.25  ...   
203892                    158.94                      0.41  ...   

        LAYER_5_EJECTARAD_REL   CRATER_NAME    RADIUS          X          Y  \
203886                    NaN  Schiaparelli  222880.0  16.799999  -2.508000   
203887                    NaN       Newcomb  128225.0   1.074000 -24.239000   
203888                    NaN   Flaugergues  118030.0  19.222000 -16.799000   
203890                    NaN           NaN   87275.0   8.507000 -23.118000   
203892                    NaN           NaN   83200.0   1.642000 -18.235001   

        TYPE  STATUS  LRD_MORPH  ORIGIN  ADDING  
203886   3.0  Buried       None    None     0.0  
203887   3.0  Buried       None    None     0.0  
203888   3.0  Buried       None    None     0.0  
203890   3.0  Buried       None    None     0.0  
203892   3.0  Buried       None    None     0.0  

[5 rows x 78 columns]

In [37]:
import numpy as np
import cv2
#BGR
color_dict = {'Other':(255,0,255),'Secondary':(0,0,255),'Buried':(255,0,0),'Layered':(0,255,0)}
def create_tile(MINLAT,MAXLAT,MINLON,MAXLON,new_df,files):
    print(MINLAT,MAXLAT,MINLON,MAXLON)
#     MINLAT = -30
#     MAXLAT = 0

#     MINLON = 0 
#     MAXLON = 30
    MINDIAM = 4
    MAXDIAM = 64
    f_df = new_df[(MINLAT<=new_df['LATITUDE_CIRCLE_IMAGE']) &(new_df['LATITUDE_CIRCLE_IMAGE']<=MAXLAT)
                  &(MINLON<=new_df['LONGITUDE_CIRCLE_IMAGE']) &(new_df['LONGITUDE_CIRCLE_IMAGE']<=MAXLON)
                 &(MINDIAM<=new_df['DIAM_CIRCLE_IMAGE']) &(new_df['DIAM_CIRCLE_IMAGE']<=MAXDIAM)]
    img_new = np.zeros((7680,7680,3), np.uint8)
    for i in range(len(f_df)):
        lat = f_df.iloc[i][1]
        # print(lat)
        lon =  f_df.iloc[i][2]
        diam =  f_df.iloc[i][5]
        # print(diam)
        if (MINLAT <= float(lat) and float(lat) <= MAXLAT and MINLON <= float(lon) and float(lon) <= MAXLON):
            # print('r')
            # print(lat,lon,diam)
            x_ctr = int(7680 * abs(lon - MINLON) / (MAXLON - MINLON))
            y_ctr = int(7680 * abs(MAXLAT - lat) / (MAXLAT - MINLAT))
            # y_ctr = int(abs(lat*256))
            r = int(diam*2.1608)
            brightness = color_dict[f_df.iloc[i]['STATUS']]
            # print(x_ctr,y_ctr,r,brightness)
            thick = -1
            #cv2.circle(img, center, radius, color, thickness=1, lineType=8, shift=0)
            img_new = cv2.circle(img_new,(x_ctr,y_ctr), r, brightness, thick) 
            # if(i==4):
            #     break
    # plt.imshow(img_new)
    # plt.show()
    cv2.imwrite('out/'+files.split('.')[0]+'.png',img_new)

In [38]:
import os 
for files in os.listdir('csv_tiles'):
    try:
        temp = files.split('_')
        print(temp[3],temp[4],temp[5],temp[6])
        create_tile(int(temp[3]),int(temp[4]),int(temp[5]),int(temp[6]),new_df,files)
    except Exception as e:
        print(e)
        continue
        # break

-30 0 120 150
-30 0 120 150
0 30 -150 -120
0 30 -150 -120
0 30 60 90
0 30 60 90
-30 0 -30 0
-30 0 -30 0
0 30 150 180
0 30 150 180
0 30 -90 -60
0 30 -90 -60
0 30 120 150
0 30 120 150
0 30 90 120
0 30 90 120
-30 0 -150 -120
-30 0 -150 -120
-30 0 -90 -60
-30 0 -90 -60
0 30 -180 -150
0 30 -180 -150
-30 0 30 60
-30 0 30 60
-30 0 150 180
-30 0 150 180
0 30 -30 0
0 30 -30 0
-30 0 0 30
-30 0 0 30
0 30 0 30
0 30 0 30
0 30 -60 -30
0 30 -60 -30
0 30 -120 -90
0 30 -120 -90
-30 0 -60 -30
-30 0 -60 -30
-30 0 -120 -90
-30 0 -120 -90
list index out of range
0 30 30 60
0 30 30 60
-30 0 -180 -150
-30 0 -180 -150
-30 0 60 90
-30 0 60 90
-30 0 90 120
-30 0 90 120


In [191]:
MINLAT = 0
MAXLAT = 30

MINLON = 60
MAXLON = 90
f_df = new_df[(MINLAT<=new_df['LATITUDE_CIRCLE_IMAGE']) &(new_df['LATITUDE_CIRCLE_IMAGE']<=MAXLAT)&(MINLON<=new_df['LONGITUDE_CIRCLE_IMAGE']) &(new_df['LONGITUDE_CIRCLE_IMAGE']<=MAXLON)]
print(len(f_df))
img = np.zeros((7680,7680,3))
for i in range(len(f_df)):
    lat = f_df.iloc[i][1]
    # print(lat)
    lon =  f_df.iloc[i][2]
    diam =  f_df.iloc[i][5]
    print(lat,lon,diam)
    # print(diam)
    if (MINLAT <= float(lat) and float(lat) <= MAXLAT and MINLON <= float(lon) and float(lon) <= MAXLON):
        # print('r')
        x_ctr = int(abs(lon*256))
        y_ctr = int(abs(lat*256))
        r = int(diam*2.1608)
        brightness = color_dict[f_df.iloc[i]['STATUS']]
        print(x_ctr,y_ctr,r)
        thick = -1
        #cv2.circle(img, center, radius, color, thickness=1, lineType=8, shift=0)
        img_temp = cv2.circle(img,(x_ctr,y_ctr), r, brightness, thick)
        print(img_temp)
        break

8809
21.381999999999998 60.831 400.95
15572 5473 866
[[[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]
  ...
  [0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]
  ...
  [0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]
  ...
  [0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 ...

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]
  ...
  [0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]
  ...
  [0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]
  ...
  [0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]]


In [188]:
np.unique(img_temp)

array([0.])

In [177]:
# import matplotlib.pyplot as plt
# plt.imshow(img)
# plt.show()

In [178]:
cv2.imwrite('temp_img11.png',img)

True

In [50]:
def loadIm(fname, tname,out_name,split, step=512, newpx = 512, px = 7680): 
    
    # im = plt.imread('Robbins_Dataset/out/'+fname)
    #px = 2048 #im.size #TODO: FIX THIS IT WILL BREAK EVERYTHING
    # print('max: ' + str(im.max()) + ', min: ' + str(im.min()) + ', mean: ' + str(im.mean()))
    # tim = 1*(plt.imread('Robbins_Dataset/out/'+tname)>0) #makes values of target binary
    im = cv2.imread('Robbins_Dataset/out/'+fname)
    print(tname)
    tim = cv2.imread(tname)
    counter = 0
    print(im.shape)
    print(tim.shape)
    count = 0
    for y in range(0,px,step): #no need to sub 512 b/c px are mult of 512
        for x in range(0,px,step):
            
            ipath = 'multiclass_data/'+split+'/images/'
            isExist = os.path.exists(ipath)
            if not isExist:
                os.makedirs(ipath)
            cv2.imwrite(ipath+out_name+str(count+step)+'.png',im[x:x+newpx,y:y+newpx].reshape((newpx,newpx,3)))
            mpath = 'multiclass_data/'+split+'/mask/'
            isExist = os.path.exists(mpath)
            if not isExist:
                os.makedirs(mpath)
            cv2.imwrite(mpath+out_name+str(count+step)+'.png',tim[x:x+newpx,y:y+newpx].reshape((newpx,newpx,3)))
            count += 1
            # break

In [51]:
c = 0
for files in os.listdir('Robbins_Dataset/out/'):
    # if(files.split("_")[-1]=='segrng.png'):
    #     print(files)
    if(files.split("_")[-1]=='filled.png'):

        print(files)
        print(files[:-11]+'_2_32_km_segrng_8_edge.png')
        if(c<15):
            split = 'train'
        elif(c<23):
            split='val'
        else:
            split='test'
        tlist = (files.split("_")[4:8])
        for m in os.listdir('out/'):
            if(m.split("_")[3:7]==tlist):
                break
        print(m)
        loadIm(files,'out/'+m,files[:-11],split)
        c += 1
        # shutil.copy('Robbins_Dataset/out/'+files,'data/'+files)

thm_dir_N-30_300_-30_0_-60_-30_filled.png
thm_dir_N-30_300_-30_0_-60_-30_2_32_km_segrng_8_edge.png
CSV_Tile_10_-30_0_-60_-30_px.png
out/CSV_Tile_10_-30_0_-60_-30_px.png
(7680, 7680, 3)
(7680, 7680, 3)
thm_dir_N00_030_0_30_30_60_filled.png
thm_dir_N00_030_0_30_30_60_2_32_km_segrng_8_edge.png
CSV_Tile_13_0_30_30_60_px.png
out/CSV_Tile_13_0_30_30_60_px.png
(7680, 7680, 3)
(7680, 7680, 3)
thm_dir_N00_240_0_30_-120_-90_filled.png
thm_dir_N00_240_0_30_-120_-90_2_32_km_segrng_8_edge.png
CSV_Tile_20_0_30_-120_-90_px.png
out/CSV_Tile_20_0_30_-120_-90_px.png
(7680, 7680, 3)
(7680, 7680, 3)
thm_dir_N-30_030_-30_0_30_60_filled.png
thm_dir_N-30_030_-30_0_30_60_2_32_km_segrng_8_edge.png
CSV_Tile_01_-30_0_30_60_px.png
out/CSV_Tile_01_-30_0_30_60_px.png
(7680, 7680, 3)
(7680, 7680, 3)
thm_dir_N-30_090_-30_0_90_120_filled.png
thm_dir_N-30_090_-30_0_90_120_2_32_km_segrng_8_edge.png
CSV_Tile_03_-30_0_90_120_px.png
out/CSV_Tile_03_-30_0_90_120_px.png
(7680, 7680, 3)
(7680, 7680, 3)
thm_dir_N-30_000_-30_0_